str = "this is a sample string"
str.upcase!
print str + " >> "
str.gsub!(/A/, "X")
str.gsub!(/B/, "G")
str.gsub!(/C/,"J")
str.gsub!(/D/, "K")
str.gsub!(/E/, "L")
str.gsub!(/F/, "P")
str.gsub!(/G/, "I")
str.gsub!(/H/, "R")
str.gsub!(/I/, "A")
str.gsub!(/J/, "Y")
str.gsub!(/K/, "Q")
str.gsub!(/L/, "H")
str.gsub!(/M/, "M")
str.gsub!(/N/, "Z")
str.gsub!(/O/,"U")
str.gsub!(/P/, "C")
str.gsub!(/Q/, "W")
str.gsub!(/R/, "D")
str.gsub!(/S/, "F")
str.gsub!(/T/, "N")
str.gsub!(/U/, "V")
str.gsub!(/V/,"S")
str.gsub!(/W/,"B")
str.gsub!(/X/,"E")
str.gsub!(/Y/, "T")
str.gsub!(/Z/, "O")

print str